### ISSUE TITLE
circle payments app

### ISSUE THREAD

**Issue by futuresBetter** [circlefin/payments-sample-app#115]
$ git clone https://github.com/circlefin/payments-sample-app.git

**Comment by kristinfritsch** [comment]
@futuresBetter hey, can you please give more details about the issue you are seeing with this?

**Comment by futuresBetter** [comment]
Im quite new to this and think I just need a bit more time to look in to it sorry.

**Comment by kristinfritsch** [comment]
Please reach out if you still run into issues. Closing this for now.
