### ISSUE TITLE
error on make payment: unable to encrypt data

### ISSUE THREAD

**Issue by Hammad1029** [circlefin/payments-sample-app#126]
I've tried all the example cards and searched around too, but can't seem to find a solution.

**Comment by kristinfritsch** [comment]
Hey @Hammad1029 can you please post the exact error message you are seeing? [Here](https://developers.circle.com/docs/accept-card-payments-online#prepare-encryption-of-sensitive-data) is some more information on card details encryption that might help you.

**Comment by kristinfritsch** [comment]
Please also let me know which OS and Browser you are using.

**Comment by Hammad1029** [comment]
From what I can see no response is being sent by the API. In the network tab, all i can see is a html docment that from what I can tell just represents the actual error. The image of the error and the html file both are attached. I'm on Kubuntu 21.04 with Chrome 91. 
![image](https://user-images.githubusercontent.com/9150711/125610986-3a13308e-5b99-4028-b37f-81c4b09ed184.png)
`<!doctype html>
<html>

<head>
    <title>payments-sample-app - payments-sample-app</title>
    <meta data-n-head="1" charset="utf-8">
    <meta data-n-head="1" name="viewport" content="width=device-width, initial-scale=1">
    <meta data-n-head="1" data-hid="description" name="description" content="Sample App for Payments API">
    <link data-n-head="1" rel="icon" type="image/x-icon" href="/favicon.ico">
    <link data-n-head="1" rel="stylesheet" type="text/css"
        href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&amp;display=swap">
    <link data-n-head="1" rel="stylesheet" type="text/css"
        href="https://cdn.jsdelivr.net/npm/@mdi/font@latest/css/materialdesignicons.min.css">
    <link rel="preload" href="/_nuxt/runtime.js" as="script">
    <link rel="preload" href="/_nuxt/commons.app.js" as="script">
    <link rel="preload" href="/_nuxt/vendors.app.js" as="script">
    <link rel="preload" href="/_nuxt/app.js" as="script">
</head>

<body>
    <div id="__nuxt">
        <style>
            #nuxt-loading {
                visibility: hidden;
                opacity: 0;
                position: absolute;
                left: 0;
                right: 0;
                top: 0;
                bottom: 0;
                display: flex;
                justify-content: center;
                align-items: center;
                flex-direction: column;
                animation: nuxtLoadingIn 10s ease;
                -webkit-animation: nuxtLoadingIn 10s ease;
                animation-fill-mode: forwards;
                overflow: hidden;
            }

            @keyframes nuxtLoadingIn {
                0% {
                    visibility: hidden;
                    opacity: 0;
                }

                20% {
                    visibility: visible;
                    opacity: 0;
                }

                100% {
                    visibility: visible;
                    opacity: 1;
                }
            }

            @-webkit-keyframes nuxtLoadingIn {
                0% {
                    visibility: hidden;
                    opacity: 0;
                }

                20% {
                    visibility: visible;
                    opacity: 0;
                }

                100% {
                    visibility: visible;
                    opacity: 1;
                }
            }

            #nuxt-loading>div,
            #nuxt-loading>div:after {
                border-radius: 50%;
                width: 5rem;
                height: 5rem;
            }

            #nuxt-loading>div {
                font-size: 10px;
                position: relative;
                text-indent: -9999em;
                border: .5rem solid #F5F5F5;
                border-left: .5rem solid #fff;
                -webkit-transform: translateZ(0);
                -ms-transform: translateZ(0);
                transform: translateZ(0);
                -webkit-animation: nuxtLoading 1.1s infinite linear;
                animation: nuxtLoading 1.1s infinite linear;
            }

            #nuxt-loading.error>div {
                border-left: .5rem solid #ff4500;
                animation-duration: 5s;
            }

            @-webkit-keyframes nuxtLoading {
                0% {
                    -webkit-transform: rotate(0deg);
                    transform: rotate(0deg);
                }

                100% {
                    -webkit-transform: rotate(360deg);
                    transform: rotate(360deg);
                }
            }

            @keyframes nuxtLoading {
                0% {
                    -webkit-transform: rotate(0deg);
                    transform: rotate(0deg);
                }

                100% {
                    -webkit-transform: rotate(360deg);
                    transform: rotate(360deg);
                }
            }
        </style>
        <script>window.addEventListener('error', function () { var e = document.getElementById('nuxt-loading'); if (e) { e.className += ' error'; } });</script>
        <div id="nuxt-loading" aria-live="polite" role="status">
            <div>Loading...</div>
        </div>
    </div>
    <script type="text/javascript" src="/_nuxt/runtime.js"></script>
    <script type="text/javascript" src="/_nuxt/commons.app.js"></script>
    <script type="text/javascript" src="/_nuxt/vendors.app.js"></script>
    <script type="text/javascript" src="/_nuxt/app.js"></script>
</body>

</html>`

**Comment by Hammad1029** [comment]
screenshot of chrome devtools network tab 
![image](https://user-images.githubusercontent.com/9150711/125611617-7c833ab7-8249-42ae-a35a-1ad06930939b.png)

**Comment by kristinfritsch** [comment]
@Hammad1029 thank you! Sorry, I didn't mention that you need to have the developer tools open before you hit the button in the ui to see the request show up. Can you try again, please?

**Comment by Hammad1029** [comment]
> @Hammad1029 thank you! Sorry, I didn't mention that you need to have the developer tools open before you hit the button in the ui to see the request show up. Can you try again, please?

I did have it open. Every time i hit the button one of these public files show up in the network tab

**Comment by kristinfritsch** [comment]
@Hammad1029 ahh, that's right. If you click on the public file you should see a new section "Headers" with more information. Can you send me a screenshot again, please? Thanks for debugging this.

**Comment by Hammad1029** [comment]
these are the headers 
![image](https://user-images.githubusercontent.com/9150711/125731498-6fbd8a76-7ed9-4e53-83d7-9605b274f328.png)
![image](https://user-images.githubusercontent.com/9150711/125731538-a9248229-e802-4fbe-a299-a27d58ab14dd.png)
and this is the preview, which as you can see is just a spinner that keeps spinning
![image](https://user-images.githubusercontent.com/9150711/125731646-cbef7ae8-a865-4352-b6da-31f5b5b7d495.png)

**Comment by kristinfritsch** [comment]
@Hammad1029 thanks for posting the screenshots looks like the request url is pointing to your local machine instead of `https://api-sandbox.circle.com`. In your `nuxt.config.js` do you see this entry?
```
  env: {
    baseUrl: process.env.BASE_URL || 'https://api-sandbox.circle.com',
  },
```

Try to change it to and see if that fixes it:
```
  env: {
    baseUrl: 'https://api-sandbox.circle.com'
  },
```

**Comment by Hammad1029** [comment]
Same error still. And even after this change it's trying to send the request to my local network. It might be possible that this is because of my company's network security settings but it's unlikely. either way will try it at home too and lyk

**Comment by kristinfritsch** [comment]
@Hammad1029 I suspect env vars work differently on your machine.
You can also try to hardcode here https://github.com/circlefin/payments-sample-app/blob/master/lib/apiTarget.ts#L12 
Instead of `return process.env.baseUrl` > `return 'https://api-sandbox.circle.com'`

**Comment by Hammad1029** [comment]
yep that did the trick. thanks!

**Comment by lukeburns** [comment]
For others running into this. Mine was serving from 192.168.1.-, so I replaced
```
if (window.location && window.location.hostname === 'localhost') {
    return process.env.baseUrl
}
````
with
```
if (process.env.baseUrl) {
    return process.env.baseUrl
}
```

**Comment by projetAziz** [comment]
can u please help me 
i have this erreur 
"request body contains unprocessable entity"

**Comment by AndrewMTA** [comment]
I keep running into a similar issue.  I went through all the solutions posted and am still running into "unable to encrypt data"

**Comment by usagiryu** [comment]
Use localhost instead of your local IP address will resolve the issue
