### ISSUE TITLE
Invalid request entity. billingAddress.phone may not be empty

### ISSUE THREAD

**Issue by fuJiin** [circlefin/payments-sample-app#20]
I'm getting this error when trying to add or charge a card, even though is no field for billing address on the forms.

<img width="612" alt="Screen Shot 2020-03-25 at 3 21 43 PM" src="https://user-images.githubusercontent.com/203277/77591122-8a2f3000-6eac-11ea-94f7-4e3f1463c1e6.png">

**Comment by kristinfritsch** [comment]
hey @fuJiin, thanks for reporting the issue. We are looking into it and will get back to you.

**Comment by kristinfritsch** [comment]
@fuJiin sorry for not getting back earlier. Should be fixed now. Feel free to reopen the issue if you still see it.
