### ISSUE TITLE
Error while run the Payment-sample-app

### ISSUE THREAD

**Issue by Tanvirhuda** [circlefin/payments-sample-app#215]
I am getting the following error while try to run the Payment-sample-app 

I have node v18 installed 

Running "Yarn Dev" command giving me the following error 

yarn install v1.22.18
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.22s.
sonia@Sonias-Air payments-sample-app % yarn dev
yarn run v1.22.18
$ cross-env NODE_ENV=development nuxt

 FATAL  details.family.toLowerCase is not a function                                                                                                       01:25:34

  at node_modules/ip/lib/ip.js:385:39
  at Array.filter (<anonymous>)
  at node_modules/ip/lib/ip.js:384:37
  at Array.map (<anonymous>)
  at ip.address (node_modules/ip/lib/ip.js:379:37)
  at Listener.computeURL (node_modules/@nuxt/server/dist/server.js:469:60)
  at Listener.listen (node_modules/@nuxt/server/dist/server.js:510:10)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Server.listen (node_modules/@nuxt/server/dist/server.js:973:5)
  at async Object._listenDev (node_modules/@nuxt/cli/dist/cli-dev.js:86:5)

   ╭─────────────────────────────────────────────────────────────╮
   │                                                             │
   │   ✖ Nuxt Fatal Error                                        │
   │                                                             │
   │   TypeError: details.family.toLowerCase is not a function   │
   │                                                             │
   ╰─────────────────────────────────────────────────────────────╯

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kristinfritsch** [comment]
hey @Tanvirhuda, this app is currently developed and tested for node 16.13.0 (https://github.com/circlefin/payments-sample-app/blob/master/.nvmrc) We recommend using a node version manager like [nvm](https://github.com/nvm-sh/nvm) in order to run the app with the required node version.
