### ISSUE TITLE
Message: Unable to encrypt data

### ISSUE THREAD

**Issue by Dhvanit41** [circlefin/payments-sample-app#216]
I am getting this error while I try to fund my dummy wallet through the virtual send box API

version node:16.14.2
npm - 8.5.0
![circleerror](https://user-images.githubusercontent.com/50017804/169015238-1cedb6d1-c002-4194-abad-5443ef5af8b9.png)

**Comment by kristinfritsch** [comment]
Please see https://github.com/circlefin/payments-sample-app/issues/126
