### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by kingsmao** [circlefin/payments-sample-app#218]
Hello cricle dev!
I applyed a test-apikey,and use this payments-sample-app.
I enter my test-api-key at payments-sample-app but It showed error message by any endpoint 
error message : {"code":2,"message":"401 Unauthorized. errId: 2b78e9c7-6288-ffbf-55b1-a11791330f42"}
please help 😭

**Comment by kristinfritsch** [comment]
hey @kingsmao is this still an issue? Have you tried to generate a new test api key?

**Comment by kingsmao** [comment]
hi there @kristinfritsch  yes, but I don't use it anymore, I integrated the api manually
