### ISSUE TITLE
Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.

### ISSUE THREAD

**Issue by slefcourt27** [circlefin/payments-sample-app#69]
Hello, 

I'm trying to test the API by running this sample payments app, but when I try to add a card or make a payment, the following message appears:  "Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded."

Please advise.

Samuel

**Comment by kristinfritsch** [comment]
Hi @slefcourt27, looks like the `publicKey` can not be decoded. Can you please check the network tab to see if `https://api-sandbox.circle.com/v1/encryption/public` returns data?

**Comment by slefcourt27** [comment]
@kristinfritsch Thanks for responding! I did try but I got this in return: {"code":401,"message":"Malformed authorization. Is the authorization type missing?"}

**Comment by kristinfritsch** [comment]
@slefcourt27 sorry for not getting back earlier. Did you add you API key in the settings?

<img width="481" alt="Screen Shot 2020-08-14 at 20 08 39" src="https://user-images.githubusercontent.com/60018266/90279707-fd403f80-de69-11ea-8983-db6236ea92da.png">

**Comment by slefcourt27** [comment]
@kristinfritsch No worries.  Yes I did put my API key in the settings.

**Comment by kristinfritsch** [comment]
@slefcourt27 hmm, does the request contain the `authorization` header? 'https://api-sandbox.circle.com/v1/encryption/public' -H 'authorization: Bearer QVBJX0tFWTo0OThkZTJiYzEzMTA5ZjFiNzMwYzQzZnY4ZjA4OGM1ZToyYWZiOTlmMDA0MjY5MGRhNjRmMTFlODFlMzQ2Mjc0YV'

**Comment by kristinfritsch** [comment]
Haven't heard back in a while. Please reopen if you are still seeing this issue.
